spring.application.name=delivery-service
server.port=8080

spring.data.mongodb.uri=mongodb://mongo:mongo123@localhost:27017/notification_db?authSource=admin

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123

rabbitmq.queue.notification=notification.created